"""empty message

Revision ID: 6eb4970d10d9
Revises: e51f7fd3c47f
Create Date: 2025-04-12 14:08:07.327667

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6eb4970d10d9'
down_revision = 'e51f7fd3c47f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('parents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('siswa_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['siswa_id'], ['siswa.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('parents')
    # ### end Alembic commands ###
